from typing import Protocol


class Optimizer(Protocol):
    @property
    def learning_rate(self) -> float: ...

    @learning_rate.setter
    def learning_rate(self, value: float) -> None: ...

    def zero_grad(self) -> None: ...

    def step(self) -> None: ...
